services:
  postgres:
    image: postgres:16-alpine
    container_name: zeytin_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zeytin_admin
    ports:
      - '5432:5432'
    volumes:
      - zeytin_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: zeytin_redis
    restart: unless-stopped
    ports:
      - '6379:6379'

volumes:
  zeytin_pg_data:
